@startuml
!include /Users/kenzhou/Documents/Codes/C4-PlantUML/C4_Container.puml

Container(containerAlias, "Label", "Technology", "Optional Description")
System(systemAlias, "Label", "Optional Description")

Rel(personAlias, containerAlias, "Label", "Optional Technology")
@enduml